name = "Titan"
uuid = "bfe7e8f3-634c-4759-86cf-c7631eccc6cf"
authors = ["Damir Akchurin <akchurinda@gmail.com>"]
version = "0.1.0"

[deps]
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StringDistances = "88034a9c-02f8-509d-84a9-84ec65e18404"
StyledStrings = "f489334b-da3d-4c2e-b8f0-e476e12c162b"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[extensions]
TitanMakieExtension = "Makie"

[compat]
OrderedCollections = "1.8.1"
StaticArrays = "1.9.14"
StringDistances = "0.11.3"
StyledStrings = "1.11.0"
julia = "1.11"

[extras]
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[test]
test = ["Test", "FiniteDiff", "ForwardDiff", "ReverseDiff"]
